import { NextResponse } from "next/server";
import { draftMode } from "next/headers";
import { getAuthorUser } from "@/lib/authorAuth";
import { DRAFT_RETRY_COOKIE } from "@/lib/draftCookies";

/**
 * How long the "we already tried" marker lasts. Long enough that a broken
 * enable cannot bounce the author around, short enough to be forgotten.
 */
const RETRY_COOKIE_MAX_AGE = 30;

/**
 * Where to send the author back to. Untrusted — it arrives in a query string —
 * so only a plain path is allowed. `//evil.com` and `/\evil.com` are both read
 * as protocol-relative URLs by browsers, which is exactly the open redirect
 * this rejects.
 */
function safeReturnPath(value: string | null): string {
  if (!value || !value.startsWith("/")) return "/";
  if (value.startsWith("//") || value.startsWith("/\\")) return "/";
  return value;
}

/**
 * Re-issue the Draft Mode cookie for an already-signed-in author.
 *
 * Draft Mode alone is a poor session: its cookie dies with the browser and its
 * value is regenerated by every build. `proxy.ts` notices when a valid Supabase
 * session has outlived it and bounces through here, which is what makes staying
 * signed in survive a redeploy.
 */
export async function GET(request: Request) {
  const url = new URL(request.url);
  const target = new URL(safeReturnPath(url.searchParams.get("next")), url.origin);

  if (await getAuthorUser()) {
    const draft = await draftMode();
    draft.enable();
  }

  const response = NextResponse.redirect(target, 307);
  response.cookies.set(DRAFT_RETRY_COOKIE, "1", {
    httpOnly: true,
    sameSite: "lax",
    secure: process.env.NODE_ENV === "production",
    path: "/",
    maxAge: RETRY_COOKIE_MAX_AGE,
  });

  return response;
}
