import { NextResponse, type NextRequest } from "next/server";
import { isAuthorUser } from "@/lib/authorAuth";
import { DRAFT_MODE_COOKIE, DRAFT_RETRY_COOKIE } from "@/lib/draftCookies";
import { createProxySupabase } from "@/lib/supabaseServer";

/**
 * Keeps the author signed in.
 *
 * Two jobs, both invisible when they work:
 *
 * 1. Rotate the Supabase session. Access tokens last an hour; refreshing them
 *    here — ahead of every render — is what turns "signed in" into something
 *    that outlives a closed browser.
 * 2. Re-issue Draft Mode. Its cookie dies with the browser and its value is
 *    regenerated by every `next build`, so a perfectly good session routinely
 *    finds itself without one. Rather than making the author sign in again,
 *    bounce once through `/api/auth/draft`, which mints a fresh one.
 *
 * Readers never reach any of it: with no Supabase cookie there is nothing to
 * refresh, and the request goes straight through.
 */
export async function proxy(request: NextRequest) {
  const signedIn = request.cookies
    .getAll()
    .some((cookie) => cookie.name.startsWith("sb-"));

  if (!signedIn) return NextResponse.next();

  const { supabase, applyTo } = createProxySupabase(request);
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const response = applyTo(NextResponse.next());

  if (!isAuthorUser(user)) return response;
  if (request.cookies.has(DRAFT_MODE_COOKIE)) return response;
  if (request.cookies.has(DRAFT_RETRY_COOKIE)) return response;

  // Only top-level page loads. Draft Mode changes what a document renders, so
  // redirecting a prefetch, an image, or a fetch() would achieve nothing.
  if (request.method !== "GET") return response;
  if (request.headers.get("sec-fetch-dest") !== "document") return response;

  const target = new URL("/api/auth/draft", request.url);
  target.searchParams.set(
    "next",
    `${request.nextUrl.pathname}${request.nextUrl.search}`
  );

  // The refreshed cookies ride along, or this round trip would undo the refresh
  // it just performed.
  return applyTo(NextResponse.redirect(target, 307));
}

export const config = {
  matcher: [
    /*
     * Everything except API routes (which read the session themselves), Next's
     * own assets, and static files — none of which render drafts.
     */
    "/((?!api/|_next/|favicon.ico|feed.xml|sitemap.xml|.*\\.(?:png|jpe?g|gif|svg|webp|avif|ico|txt|xml|woff2?)$).*)",
  ],
};
